// Copyright 2022 Listware

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: pbtypes/pbresult.proto

package pbtypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Topic     string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Key       string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ReplyResult) Reset() {
	*x = ReplyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbtypes_pbresult_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyResult) ProtoMessage() {}

func (x *ReplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_pbtypes_pbresult_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyResult.ProtoReflect.Descriptor instead.
func (*ReplyResult) Descriptor() ([]byte, []int) {
	return file_pbtypes_pbresult_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyResult) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReplyResult) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReplyResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplyResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FunctionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyEgress *ReplyResult `protobuf:"bytes,1,opt,name=reply_egress,json=replyEgress,proto3" json:"reply_egress,omitempty"`
	Complete    bool         `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Errors      []string     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *FunctionResult) Reset() {
	*x = FunctionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbtypes_pbresult_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResult) ProtoMessage() {}

func (x *FunctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pbtypes_pbresult_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResult.ProtoReflect.Descriptor instead.
func (*FunctionResult) Descriptor() ([]byte, []int) {
	return file_pbtypes_pbresult_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionResult) GetReplyEgress() *ReplyResult {
	if x != nil {
		return x.ReplyEgress
	}
	return nil
}

func (x *FunctionResult) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *FunctionResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_pbtypes_pbresult_proto protoreflect.FileDescriptor

var file_pbtypes_pbresult_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x22, 0x63, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x0c, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x5f, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x45, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x42, 0x45, 0x0a, 0x10, 0x6f, 0x72, 0x67, 0x2e,
	0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x42, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x2e, 0x66, 0x67, 0x2d, 0x74, 0x65, 0x63,
	0x68, 0x2e, 0x72, 0x75, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x62, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbtypes_pbresult_proto_rawDescOnce sync.Once
	file_pbtypes_pbresult_proto_rawDescData = file_pbtypes_pbresult_proto_rawDesc
)

func file_pbtypes_pbresult_proto_rawDescGZIP() []byte {
	file_pbtypes_pbresult_proto_rawDescOnce.Do(func() {
		file_pbtypes_pbresult_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbtypes_pbresult_proto_rawDescData)
	})
	return file_pbtypes_pbresult_proto_rawDescData
}

var file_pbtypes_pbresult_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbtypes_pbresult_proto_goTypes = []interface{}{
	(*ReplyResult)(nil),    // 0: org.listware.sdk.pbtypes.ReplyResult
	(*FunctionResult)(nil), // 1: org.listware.sdk.pbtypes.FunctionResult
}
var file_pbtypes_pbresult_proto_depIdxs = []int32{
	0, // 0: org.listware.sdk.pbtypes.FunctionResult.reply_egress:type_name -> org.listware.sdk.pbtypes.ReplyResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pbtypes_pbresult_proto_init() }
func file_pbtypes_pbresult_proto_init() {
	if File_pbtypes_pbresult_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbtypes_pbresult_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbtypes_pbresult_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbtypes_pbresult_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbtypes_pbresult_proto_goTypes,
		DependencyIndexes: file_pbtypes_pbresult_proto_depIdxs,
		MessageInfos:      file_pbtypes_pbresult_proto_msgTypes,
	}.Build()
	File_pbtypes_pbresult_proto = out.File
	file_pbtypes_pbresult_proto_rawDesc = nil
	file_pbtypes_pbresult_proto_goTypes = nil
	file_pbtypes_pbresult_proto_depIdxs = nil
}
