// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbqdsl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QdslServiceClient is the client API for QdslService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QdslServiceClient interface {
	Qdsl(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Elements, error)
}

type qdslServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQdslServiceClient(cc grpc.ClientConnInterface) QdslServiceClient {
	return &qdslServiceClient{cc}
}

func (c *qdslServiceClient) Qdsl(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Elements, error) {
	out := new(Elements)
	err := c.cc.Invoke(ctx, "/org.listware.sdk.pbcmdb.pbqdsl.QdslService/Qdsl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QdslServiceServer is the server API for QdslService service.
// All implementations must embed UnimplementedQdslServiceServer
// for forward compatibility
type QdslServiceServer interface {
	Qdsl(context.Context, *Query) (*Elements, error)
	mustEmbedUnimplementedQdslServiceServer()
}

// UnimplementedQdslServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQdslServiceServer struct {
}

func (UnimplementedQdslServiceServer) Qdsl(context.Context, *Query) (*Elements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Qdsl not implemented")
}
func (UnimplementedQdslServiceServer) mustEmbedUnimplementedQdslServiceServer() {}

// UnsafeQdslServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QdslServiceServer will
// result in compilation errors.
type UnsafeQdslServiceServer interface {
	mustEmbedUnimplementedQdslServiceServer()
}

func RegisterQdslServiceServer(s grpc.ServiceRegistrar, srv QdslServiceServer) {
	s.RegisterService(&QdslService_ServiceDesc, srv)
}

func _QdslService_Qdsl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdslServiceServer).Qdsl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.listware.sdk.pbcmdb.pbqdsl.QdslService/Qdsl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdslServiceServer).Qdsl(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

// QdslService_ServiceDesc is the grpc.ServiceDesc for QdslService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QdslService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.listware.sdk.pbcmdb.pbqdsl.QdslService",
	HandlerType: (*QdslServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Qdsl",
			Handler:    _QdslService_Qdsl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbcmdb/pbqdsl/service.proto",
}
