// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbcmdb/pbqdsl/service.proto

package org.listware.sdk.pbcmdb.pbqdsl;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033pbcmdb/pbqdsl/service.proto\022\036org.listw" +
      "are.sdk.pbcmdb.pbqdsl\032\032pbcmdb/pbqdsl/pbq" +
      "dsl.proto2h\n\013QdslService\022Y\n\004Qdsl\022%.org.l" +
      "istware.sdk.pbcmdb.pbqdsl.Query\032(.org.li" +
      "stware.sdk.pbcmdb.pbqdsl.Elements\"\000BZ\n\036o" +
      "rg.listware.sdk.pbcmdb.pbqdslB\007ServiceZ/" +
      "git.fg-tech.ru/listware/proto/sdk/pbcmdb" +
      "/pbqdslb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.listware.sdk.pbcmdb.pbqdsl.QDSL.getDescriptor(),
        }, assigner);
    org.listware.sdk.pbcmdb.pbqdsl.QDSL.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
