// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbcmdb/pbfinder/service.proto

package org.listware.sdk.pbcmdb.pbfinder;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035pbcmdb/pbfinder/service.proto\022 org.lis" +
      "tware.sdk.pbcmdb.pbfinder\032\036pbcmdb/pbfind" +
      "er/pbfinder.proto2q\n\rFinderService\022`\n\005Li" +
      "nks\022).org.listware.sdk.pbcmdb.pbfinder.R" +
      "equest\032*.org.listware.sdk.pbcmdb.pbfinde" +
      "r.Response\"\000B^\n org.listware.sdk.pbcmdb." +
      "pbfinderB\007ServiceZ1git.fg-tech.ru/listwa" +
      "re/proto/sdk/pbcmdb/pbfinderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.listware.sdk.pbcmdb.pbfinder.Finder.getDescriptor(),
        }, assigner);
    org.listware.sdk.pbcmdb.pbfinder.Finder.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
