// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbfinder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinderServiceClient is the client API for FinderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinderServiceClient interface {
	Links(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type finderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinderServiceClient(cc grpc.ClientConnInterface) FinderServiceClient {
	return &finderServiceClient{cc}
}

func (c *finderServiceClient) Links(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/org.listware.sdk.pbcmdb.pbfinder.FinderService/Links", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinderServiceServer is the server API for FinderService service.
// All implementations must embed UnimplementedFinderServiceServer
// for forward compatibility
type FinderServiceServer interface {
	Links(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFinderServiceServer()
}

// UnimplementedFinderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFinderServiceServer struct {
}

func (UnimplementedFinderServiceServer) Links(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Links not implemented")
}
func (UnimplementedFinderServiceServer) mustEmbedUnimplementedFinderServiceServer() {}

// UnsafeFinderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinderServiceServer will
// result in compilation errors.
type UnsafeFinderServiceServer interface {
	mustEmbedUnimplementedFinderServiceServer()
}

func RegisterFinderServiceServer(s grpc.ServiceRegistrar, srv FinderServiceServer) {
	s.RegisterService(&FinderService_ServiceDesc, srv)
}

func _FinderService_Links_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServiceServer).Links(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.listware.sdk.pbcmdb.pbfinder.FinderService/Links",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServiceServer).Links(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FinderService_ServiceDesc is the grpc.ServiceDesc for FinderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.listware.sdk.pbcmdb.pbfinder.FinderService",
	HandlerType: (*FinderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Links",
			Handler:    _FinderService_Links_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbcmdb/pbfinder/service.proto",
}
