//
//  Copyright 2023 NJWS Inc.
//  Copyright 2022 Listware

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: pbcmdb/pbcmdb.proto

package pbcmdb

import (
	pbtypes "git.fg-tech.ru/listware/proto/sdk/pbtypes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_CREATE         Method = 0
	Method_CREATE_CHILD   Method = 1
	Method_UPDATE         Method = 2
	Method_REPLACE        Method = 3
	Method_DELETE         Method = 4
	Method_CREATE_TRIGGER Method = 5
	Method_DELETE_TRIGGER Method = 6
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "CREATE",
		1: "CREATE_CHILD",
		2: "UPDATE",
		3: "REPLACE",
		4: "DELETE",
		5: "CREATE_TRIGGER",
		6: "DELETE_TRIGGER",
	}
	Method_value = map[string]int32{
		"CREATE":         0,
		"CREATE_CHILD":   1,
		"UPDATE":         2,
		"REPLACE":        3,
		"DELETE":         4,
		"CREATE_TRIGGER": 5,
		"DELETE_TRIGGER": 6,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_pbcmdb_pbcmdb_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_pbcmdb_pbcmdb_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{0}
}

type ObjectMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  Method `protobuf:"varint,1,opt,name=method,proto3,enum=org.listware.sdk.pbcmdb.Method" json:"method,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// add links from func to object uuid
	Functions []*pbtypes.FunctionMessage `protobuf:"bytes,5,rep,name=functions,proto3" json:"functions,omitempty"`
}

func (x *ObjectMessage) Reset() {
	*x = ObjectMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMessage) ProtoMessage() {}

func (x *ObjectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMessage.ProtoReflect.Descriptor instead.
func (*ObjectMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMessage) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_CREATE
}

func (x *ObjectMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObjectMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ObjectMessage) GetFunctions() []*pbtypes.FunctionMessage {
	if x != nil {
		return x.Functions
	}
	return nil
}

type TypeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  Method `protobuf:"varint,1,opt,name=method,proto3,enum=org.listware.sdk.pbcmdb.Method" json:"method,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// add links from func to object uuid
	Functions []*pbtypes.FunctionMessage `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
}

func (x *TypeMessage) Reset() {
	*x = TypeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMessage) ProtoMessage() {}

func (x *TypeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMessage.ProtoReflect.Descriptor instead.
func (*TypeMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{1}
}

func (x *TypeMessage) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_CREATE
}

func (x *TypeMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TypeMessage) GetFunctions() []*pbtypes.FunctionMessage {
	if x != nil {
		return x.Functions
	}
	return nil
}

type LinkMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  Method `protobuf:"varint,1,opt,name=method,proto3,enum=org.listware.sdk.pbcmdb.Method" json:"method,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	To      string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *LinkMessage) Reset() {
	*x = LinkMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkMessage) ProtoMessage() {}

func (x *LinkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkMessage.ProtoReflect.Descriptor instead.
func (*LinkMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{2}
}

func (x *LinkMessage) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_CREATE
}

func (x *LinkMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LinkMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *LinkMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Trigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         string                `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	FunctionType *pbtypes.FunctionType `protobuf:"bytes,2,opt,name=function_type,json=functionType,proto3" json:"function_type,omitempty"`
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{3}
}

func (x *Trigger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Trigger) GetFunctionType() *pbtypes.FunctionType {
	if x != nil {
		return x.FunctionType
	}
	return nil
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Rev string `protobuf:"bytes,3,opt,name=rev,proto3" json:"rev,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{4}
}

func (x *Meta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Meta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Meta) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Collection string `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Payload    []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta    *Meta  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RegisterTypeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Async       bool         `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	Router      bool         `protobuf:"varint,3,opt,name=router,proto3" json:"router,omitempty"`
	TypeMessage *TypeMessage `protobuf:"bytes,4,opt,name=type_message,json=typeMessage,proto3" json:"type_message,omitempty"`
}

func (x *RegisterTypeMessage) Reset() {
	*x = RegisterTypeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTypeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTypeMessage) ProtoMessage() {}

func (x *RegisterTypeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTypeMessage.ProtoReflect.Descriptor instead.
func (*RegisterTypeMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterTypeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterTypeMessage) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *RegisterTypeMessage) GetRouter() bool {
	if x != nil {
		return x.Router
	}
	return false
}

func (x *RegisterTypeMessage) GetTypeMessage() *TypeMessage {
	if x != nil {
		return x.TypeMessage
	}
	return nil
}

type RegisterObjectMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Async         bool           `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	Router        bool           `protobuf:"varint,3,opt,name=router,proto3" json:"router,omitempty"`
	ObjectMessage *ObjectMessage `protobuf:"bytes,4,opt,name=object_message,json=objectMessage,proto3" json:"object_message,omitempty"`
}

func (x *RegisterObjectMessage) Reset() {
	*x = RegisterObjectMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterObjectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterObjectMessage) ProtoMessage() {}

func (x *RegisterObjectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterObjectMessage.ProtoReflect.Descriptor instead.
func (*RegisterObjectMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterObjectMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterObjectMessage) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *RegisterObjectMessage) GetRouter() bool {
	if x != nil {
		return x.Router
	}
	return false
}

func (x *RegisterObjectMessage) GetObjectMessage() *ObjectMessage {
	if x != nil {
		return x.ObjectMessage
	}
	return nil
}

type RegisterLinkMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Async       bool         `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	LinkMessage *LinkMessage `protobuf:"bytes,4,opt,name=link_message,json=linkMessage,proto3" json:"link_message,omitempty"`
}

func (x *RegisterLinkMessage) Reset() {
	*x = RegisterLinkMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterLinkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLinkMessage) ProtoMessage() {}

func (x *RegisterLinkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLinkMessage.ProtoReflect.Descriptor instead.
func (*RegisterLinkMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterLinkMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterLinkMessage) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *RegisterLinkMessage) GetLinkMessage() *LinkMessage {
	if x != nil {
		return x.LinkMessage
	}
	return nil
}

type RegisterFunctionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Async           bool                     `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	FunctionMessage *pbtypes.FunctionMessage `protobuf:"bytes,4,opt,name=function_message,json=functionMessage,proto3" json:"function_message,omitempty"`
}

func (x *RegisterFunctionMessage) Reset() {
	*x = RegisterFunctionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterFunctionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFunctionMessage) ProtoMessage() {}

func (x *RegisterFunctionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFunctionMessage.ProtoReflect.Descriptor instead.
func (*RegisterFunctionMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterFunctionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterFunctionMessage) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *RegisterFunctionMessage) GetFunctionMessage() *pbtypes.FunctionMessage {
	if x != nil {
		return x.FunctionMessage
	}
	return nil
}

type RegisterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeMessages     []*RegisterTypeMessage     `protobuf:"bytes,1,rep,name=type_messages,json=typeMessages,proto3" json:"type_messages,omitempty"`
	ObjectMessages   []*RegisterObjectMessage   `protobuf:"bytes,2,rep,name=object_messages,json=objectMessages,proto3" json:"object_messages,omitempty"`
	LinkMessages     []*RegisterLinkMessage     `protobuf:"bytes,3,rep,name=link_messages,json=linkMessages,proto3" json:"link_messages,omitempty"`
	FunctionMessages []*RegisterFunctionMessage `protobuf:"bytes,4,rep,name=function_messages,json=functionMessages,proto3" json:"function_messages,omitempty"`
}

func (x *RegisterMessage) Reset() {
	*x = RegisterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbcmdb_pbcmdb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMessage) ProtoMessage() {}

func (x *RegisterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pbcmdb_pbcmdb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMessage.ProtoReflect.Descriptor instead.
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return file_pbcmdb_pbcmdb_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterMessage) GetTypeMessages() []*RegisterTypeMessage {
	if x != nil {
		return x.TypeMessages
	}
	return nil
}

func (x *RegisterMessage) GetObjectMessages() []*RegisterObjectMessage {
	if x != nil {
		return x.ObjectMessages
	}
	return nil
}

func (x *RegisterMessage) GetLinkMessages() []*RegisterLinkMessage {
	if x != nil {
		return x.LinkMessages
	}
	return nil
}

func (x *RegisterMessage) GetFunctionMessages() []*RegisterFunctionMessage {
	if x != nil {
		return x.FunctionMessages
	}
	return nil
}

var File_pbcmdb_pbcmdb_proto protoreflect.FileDescriptor

var file_pbcmdb_pbcmdb_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x1a, 0x18,
	0x70, 0x62, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x01, 0x0a, 0x0d, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62,
	0x63, 0x6d, 0x64, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x47, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xbd,
	0x01, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x47, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x98,
	0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6a, 0x0a, 0x07, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4b, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73,
	0x64, 0x6b, 0x2e, 0x70, 0x62, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65,
	0x76, 0x22, 0x55, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x57, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72,
	0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x9c, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x79,
	0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xa4, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73,
	0x79, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x0e, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x61, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x47, 0x0a, 0x0c, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70,
	0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x0b, 0x6c, 0x69, 0x6e, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x95,
	0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73,
	0x79, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63,
	0x12, 0x54, 0x0a, 0x10, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xef, 0x02, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x51, 0x0a, 0x0d, 0x74, 0x79,
	0x70, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x0c, 0x74, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x57, 0x0a,
	0x0f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x51, 0x0a, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x6c, 0x69, 0x6e,
	0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x5d, 0x0a, 0x11, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x10, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x73, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x49, 0x4c, 0x44, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c,
	0x45, 0x54, 0x45, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f,
	0x54, 0x52, 0x49, 0x47, 0x47, 0x45, 0x52, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x45, 0x4c,
	0x45, 0x54, 0x45, 0x5f, 0x54, 0x52, 0x49, 0x47, 0x47, 0x45, 0x52, 0x10, 0x06, 0x42, 0x49, 0x0a,
	0x17, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x42, 0x04, 0x43, 0x6f, 0x72, 0x65, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x2e, 0x66, 0x67, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x72, 0x75, 0x2f, 0x6c,
	0x69, 0x73, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x64,
	0x6b, 0x2f, 0x70, 0x62, 0x63, 0x6d, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbcmdb_pbcmdb_proto_rawDescOnce sync.Once
	file_pbcmdb_pbcmdb_proto_rawDescData = file_pbcmdb_pbcmdb_proto_rawDesc
)

func file_pbcmdb_pbcmdb_proto_rawDescGZIP() []byte {
	file_pbcmdb_pbcmdb_proto_rawDescOnce.Do(func() {
		file_pbcmdb_pbcmdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbcmdb_pbcmdb_proto_rawDescData)
	})
	return file_pbcmdb_pbcmdb_proto_rawDescData
}

var file_pbcmdb_pbcmdb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pbcmdb_pbcmdb_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pbcmdb_pbcmdb_proto_goTypes = []interface{}{
	(Method)(0),                     // 0: org.listware.sdk.pbcmdb.Method
	(*ObjectMessage)(nil),           // 1: org.listware.sdk.pbcmdb.ObjectMessage
	(*TypeMessage)(nil),             // 2: org.listware.sdk.pbcmdb.TypeMessage
	(*LinkMessage)(nil),             // 3: org.listware.sdk.pbcmdb.LinkMessage
	(*Trigger)(nil),                 // 4: org.listware.sdk.pbcmdb.Trigger
	(*Meta)(nil),                    // 5: org.listware.sdk.pbcmdb.Meta
	(*Request)(nil),                 // 6: org.listware.sdk.pbcmdb.Request
	(*Response)(nil),                // 7: org.listware.sdk.pbcmdb.Response
	(*RegisterTypeMessage)(nil),     // 8: org.listware.sdk.pbcmdb.RegisterTypeMessage
	(*RegisterObjectMessage)(nil),   // 9: org.listware.sdk.pbcmdb.RegisterObjectMessage
	(*RegisterLinkMessage)(nil),     // 10: org.listware.sdk.pbcmdb.RegisterLinkMessage
	(*RegisterFunctionMessage)(nil), // 11: org.listware.sdk.pbcmdb.RegisterFunctionMessage
	(*RegisterMessage)(nil),         // 12: org.listware.sdk.pbcmdb.RegisterMessage
	(*pbtypes.FunctionMessage)(nil), // 13: org.listware.sdk.pbtypes.FunctionMessage
	(*pbtypes.FunctionType)(nil),    // 14: org.listware.sdk.pbtypes.FunctionType
}
var file_pbcmdb_pbcmdb_proto_depIdxs = []int32{
	0,  // 0: org.listware.sdk.pbcmdb.ObjectMessage.method:type_name -> org.listware.sdk.pbcmdb.Method
	13, // 1: org.listware.sdk.pbcmdb.ObjectMessage.functions:type_name -> org.listware.sdk.pbtypes.FunctionMessage
	0,  // 2: org.listware.sdk.pbcmdb.TypeMessage.method:type_name -> org.listware.sdk.pbcmdb.Method
	13, // 3: org.listware.sdk.pbcmdb.TypeMessage.functions:type_name -> org.listware.sdk.pbtypes.FunctionMessage
	0,  // 4: org.listware.sdk.pbcmdb.LinkMessage.method:type_name -> org.listware.sdk.pbcmdb.Method
	14, // 5: org.listware.sdk.pbcmdb.Trigger.function_type:type_name -> org.listware.sdk.pbtypes.FunctionType
	5,  // 6: org.listware.sdk.pbcmdb.Response.meta:type_name -> org.listware.sdk.pbcmdb.Meta
	2,  // 7: org.listware.sdk.pbcmdb.RegisterTypeMessage.type_message:type_name -> org.listware.sdk.pbcmdb.TypeMessage
	1,  // 8: org.listware.sdk.pbcmdb.RegisterObjectMessage.object_message:type_name -> org.listware.sdk.pbcmdb.ObjectMessage
	3,  // 9: org.listware.sdk.pbcmdb.RegisterLinkMessage.link_message:type_name -> org.listware.sdk.pbcmdb.LinkMessage
	13, // 10: org.listware.sdk.pbcmdb.RegisterFunctionMessage.function_message:type_name -> org.listware.sdk.pbtypes.FunctionMessage
	8,  // 11: org.listware.sdk.pbcmdb.RegisterMessage.type_messages:type_name -> org.listware.sdk.pbcmdb.RegisterTypeMessage
	9,  // 12: org.listware.sdk.pbcmdb.RegisterMessage.object_messages:type_name -> org.listware.sdk.pbcmdb.RegisterObjectMessage
	10, // 13: org.listware.sdk.pbcmdb.RegisterMessage.link_messages:type_name -> org.listware.sdk.pbcmdb.RegisterLinkMessage
	11, // 14: org.listware.sdk.pbcmdb.RegisterMessage.function_messages:type_name -> org.listware.sdk.pbcmdb.RegisterFunctionMessage
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pbcmdb_pbcmdb_proto_init() }
func file_pbcmdb_pbcmdb_proto_init() {
	if File_pbcmdb_pbcmdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbcmdb_pbcmdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trigger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTypeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterObjectMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterLinkMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterFunctionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbcmdb_pbcmdb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbcmdb_pbcmdb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbcmdb_pbcmdb_proto_goTypes,
		DependencyIndexes: file_pbcmdb_pbcmdb_proto_depIdxs,
		EnumInfos:         file_pbcmdb_pbcmdb_proto_enumTypes,
		MessageInfos:      file_pbcmdb_pbcmdb_proto_msgTypes,
	}.Build()
	File_pbcmdb_pbcmdb_proto = out.File
	file_pbcmdb_pbcmdb_proto_rawDesc = nil
	file_pbcmdb_pbcmdb_proto_goTypes = nil
	file_pbcmdb_pbcmdb_proto_depIdxs = nil
}
